language: go
go:
    - 1.6
    - 1.7
    - 1.8
    - 1.9
    - 1.10
    - 1.11
    - 1.13
    - tip
matrix:
    fast_finish: true
    allow_failures:
        - go: tip
go_import_path: github.com/go-ldap/ldif
install:
    - go get github.com/go-asn1-ber/asn1-ber
    - go get github.com/go-ldap/ldap/v3
    - go get code.google.com/p/go.tools/cmd/cover || go get golang.org/x/tools/cmd/cover
    - go get github.com/golang/lint/golint || true
    - go build -v ./...
script:
    - make test
    - make fmt
    - make vet
    - if [ "${TRAVIS_GO_VERSION}" != "1.6" ]; then make lint; fi
